version: "3.8"
services:
  app:
    build: .
    container_name: minitwit-app-instance
    ports:
      - "8080:8080"
    networks:
      - minitwit-network

  api:
    build:
      dockerfile: api/Dockerfile
    container_name: minitwit-api-instance
    ports:
      - "5000:5000"
    networks:
      - minitwit-network

  prometheus:
    image: prom/prometheus
    container_name: minitwit-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - minitwit-network

  grafana:
    image: grafana/grafana
    container_name: minitwit-grafana
    ports:
      - "3000:3000"
    networks:
      - minitwit-network
    depends_on:
      - prometheus

networks:
  minitwit-network:
    driver: bridge
