version: "3.8"
services:
  app:
    image: fujiemei02/minitwitimage
    container_name: minitwit-app-instance
    ports:
      - "8080:8080"

  api:
    image: fujiemei02/minitwitapi
    container_name: minitwit-api-instance
    ports:
      - "5000:5000"
    