version: "3.8"
services:
   
  app:
    image: 2rius/minitwitimage:latest
      #build:
      #  dockerfile: ./Dockerfile
      #container_name: minitwit-app-instance
    ports:
      - "8080:8080"
    deploy:
      replicas: 3  # Number of instances
      restart_policy:
        condition: on-failure
    networks:
      - minitwit-network
    env_file:
      - .env
      
  api:
    image: 2rius/minitwitapi:latest
      #build:
      #  dockerfile: api/Dockerfile
      #container_name: minitwit-api-instance
    ports:
      - "5000:5000"
    deploy:
      replicas: 3  # Number of instances
      restart_policy:
        condition: on-failure
    networks:
      - minitwit-network
    env_file:
      - .env

  prometheus:
    image: prom/prometheus
    container_name: minitwit-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - minitwit-network
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana
    container_name: minitwit-grafana
    ports:
      - "3000:3000"
    networks:
      - minitwit-network
    depends_on:
      - prometheus
    deploy:
      placement:
        constraints:
          - node.role == manager



networks:
  minitwit-network:
    driver: overlay

