global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'minitwit-api'
    static_configs:
      - targets: ['api:5000']
  - job_name: 'minitwit-app'
    static_configs:
      - targets: ['app:8080']
