name: Continuous Deployment
on:
  push:
    branches:
      - ft/githubActions


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test
        run: |
          
          echo ${{ github.event.head_commit.message }}

      
