name: Continuous Deployment
on:
  push:
    branches:
      - ft/githubActions


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version:  3.9.18

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test app
        run: |
          make postgrestestinit
          sleep 10
          make createdbtest
          go run src/main.go -test true &
          pytest refactored_minitwit_tests.py
          make dropdb-test

      - name: Test api
        run: |
          make createdbtest
          go run api/api.go -test true &
          until curl -s http://localhost:5000/health > /dev/null; do
            sleep 1
          done
          cd api
          pytest api_test.py
          
