name: Compile Latex
on:
  push:
    branches:
      - paper
    paths:
      - 'report/*.tex'

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: main.tex
          working_directory: report
          args: -output-directory=build -pdf
      - name: Commit and Push PDF file
        run: |
          mv report/build/main.pdf report/build/BSc_group_m.pdf
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add report/build/BSc_group_m.pdf
          git commit -m "Automatically update pdf file" || echo "No changes to commit"
          git push