name: Compile Latex
on:
  push:
    branches:
      - paper

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: main.tex
          working_directory: report
          args: -output-directory=build -pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: report/build/main.pdf